name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submetting this issue, I will check it as soon as possible' first issue"
        pr-message: "Thank you for pulling this code hope it will help you with y' first pull request"
